// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Authenticate() {
  return window['go']['main']['App']['Authenticate']();
}

export function CheckProcessingStatus() {
  return window['go']['main']['App']['CheckProcessingStatus']();
}

export function GetComputerInformation() {
  return window['go']['main']['App']['GetComputerInformation']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
