// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Authenticate():Promise<number>;

export function CheckProcessingStatus():Promise<string>;

export function GetComputerInformation():Promise<main.ComputerInformation>;

export function GetConfig():Promise<main.Config>;

export function SaveConfig(arg1:main.Config):Promise<void>;
